[versions]
agp = "9.2.0"
kotlin = "2.3.20"

activity = "1.13.0"
app-update = "2.1.0"
app-update-ktx = "2.1.0"
appcompat = "1.8.0-alpha01"
baselineprofile = "1.5.0-alpha05"
benchmark-macro-junit4 = "1.5.0-alpha05"
browser = "1.10.0"
constraintlayout = "2.2.1"
core = "1.19.0-alpha01"
core-splashscreen = "1.2.0"
coroutines = "1.10.2"
datastore = "1.3.0-alpha07"
espresso-core = "3.7.0"
fragment = "1.8.9"
hiddenapibypass = "6.1"
junit = "1.3.0"
leakcanary = "2.14"
leanback = "1.2.0"
leanback-preference = "1.2.0"
material = "1.14.0-beta01"
monetcompat = "0.4.1"
okio = "3.17.0"
palette = "1.0.0"
preference = "1.2.1"
profileinstaller = "1.4.1"
recyclerview = "1.4.0"
review = "2.0.2"
review-ktx = "2.0.2"
serialization = "1.10.0"
startup = "1.2.0"
uiautomator = "2.4.0-beta02"
window = "1.6.0-alpha01"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-okio = { module = "androidx.datastore:datastore-core-okio", version.ref = "datastore" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
androidx-leanback-preference = { module = "androidx.leanback:leanback-preference", version.ref = "leanback-preference" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
app-update = { module = "com.google.android.play:app-update", version.ref = "app-update" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "app-update-ktx" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
material = { module = "com.google.android.material:material", version.ref = "material" }
monetcompat = { module = "com.github.KieronQuinn:MonetCompat", version.ref = "monetcompat" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
plumber-android = { module = "com.squareup.leakcanary:plumber-android", version.ref = "leakcanary" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review-ktx" }
review = { module = "com.google.android.play:review", version.ref = "review" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }